language: cpp

sudo: required

services:
  - docker

before_install:
- docker pull insighttoolkit/minimalpathextraction-test

script:
- docker run insighttoolkit/minimalpathextraction-test echo "Running Docker..."

